name: Nix

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  nix-unit:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: nix-unit
        run: nix-shell --run "nix-unit ./tests.nix"

  checks:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v30
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - name: checks
        run: nix-build checks.nix -v

  build-pages:
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    needs:
      - nix-unit
      - checks
    steps:
      - uses: cachix/install-nix-action@v30
        with:
          nix_path: nixpkgs=channel:nixos-unstable
      - uses: actions/checkout@v4.2.2
      - name: Run build
        run: nix-build ./dev -A doc
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./result

  deploy-pages:
    if: github.ref == 'refs/heads/master'
    needs: build-pages
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
